{{- if .Values.i2pd.reseed.zipfile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-reseedzip
data:
  seed.zip: |-
      {{ .Files.Get "seed.zip" | default "" | b64enc }}
{{- end }}
